<?php
function appointment_classroom_menu(){
	$items['appointment_classroom']=array(
			'title' => '教室列表',
			'page callback' => 'appointment_classroom_page',
			'access callback' => 'user_access',
			'access arguments' => array('manage classroom'),	
			'type' => MENU_NORMAL_ITEM,
	);
	$items['appointment_classroom/delete']=array(
			'title' => 'Appointment Classroom',
			'page callback' => 'delete_classroom',
			'access callback' => 'user_access',
			'access arguments' => array('manage classroom'),	
			'type' => MENU_CALLBACK,
	);
	$items['appointment_classroom/edit']=array(
			'title' => 'Appointment Classroom',
			'page callback' => 'edit_classroom',
			'access callback' => 'user_access',
			'access arguments' => array('manage classroom'),	
			'type' => MENU_CALLBACK,
	);
	return $items;
}

function appointment_classroom_permission(){
	return array(
		'manage classroom' => array(
			'title' => t('Manager classroom'),
			'description' => t('Allow users manager the list of classroom.'),
		),
	);
}

function delete_classroom($serial){
	$success = db_delete('as_classroom')
		->condition('serial',$serial)
		->execute();
	if($success!=null)
		drupal_set_message('刪除教室 '.$serial.' 成功!');
	else
		drupal_set_message('刪除教室 '.$serial.' 失敗!','error');	
	
	drupal_goto('appointment_classroom');
	return;
}

function edit_classroom($arg){
	switch($arg){
		case 'serial':
			$success = db_update('as_classroom')
				->fields(array(
					'serial' => $_POST['new_serial']
			))
			->condition('cid',$_POST['cid'],'=')
			->execute();
			if($success != null)
				drupal_set_message('更改教室編號成功!');
			else
				drupal_set_message('更改教室編號失敗!','error');
			drupal_goto('appointment_classroom');
			break;
		case 'name':
			$success = db_update('as_classroom')
				->fields(array(
					'name' => $_POST['new_name']
			))
			->condition('cid',$_POST['cid'],'=')
			->execute();
			if($success != null)
				drupal_set_message('更改教室名稱成功!');
			else
				drupal_set_message('更改教室名稱失敗!','error');
			drupal_goto('appointment_classroom');
			break;

	return;
	}
	
}

function appointment_classroom_page(){
	$result = db_query('select * from as_classroom');
	$rows = array();
	foreach($result as $row){
		$rename = '
			<center>
				<form name="edit_serial" action="appointment_classroom/edit/serial" method="post">
					更改編號為:
      		<input name="new_serial" type="text" />
        	<input name="cid" type="hidden" value="'.$row->cid.'" />
        	<input type="submit" value="更改" />
				</form>
				<form name="edit_name" action="appointment_classroom/edit/name" method="post">
					更改名稱為:
      		<input name="new_name" type="text" />
        	<input name="cid" type="hidden" value="'.$row->cid.'" />
        	<input type="submit" value="更改" />
				</form>
			</center>';
		$delete = 
			'<a href="appointment_classroom/delete/'.$row->serial.'"><img src="sites/all/modules/appointment/images/b_drop.png" /></a>';
		$rows[] = array($row->serial, $row->name,$rename,$delete);
	}
	$headers = array(
		'教室編號',
		'教室名稱',
		'',
		'刪除'
	);
	
	$output = '<h1>新增教室</h1>'; 
	$output .= drupal_render(drupal_get_form('appointment_classroom_form'));
	$output .= theme(
		'table',
		array(
			'header' => $headers,
			'rows' => $rows
		)
	);
	return $output;
}

function appointment_classroom_form($form, &$form_state){
	$form = array();
 	$form['serial'] = array(
     '#type'=>'textfield',
     '#title'=>t('教室編號'),
  );
  $form['name'] = array(
    '#type'=>'textfield',
  	'#title'=>t('教室名稱'),
  );
  $form['submit'] = array('#type'=>'submit', '#value'=>'新增');
	return $form;
}

function appointment_classroom_form_submit($form, &$form_state) {
	$nid = db_insert('as_classroom')
		->fields(array(
			'cid' => NULL,
			'serial' => $form_state['values']['serial'],
			'name' => $form_state['values']['name']
		))
		->execute();
}
