<?php
require_once(DRUPAL_ROOT.'/sites/all/modules/appointment/config.inc');

function appointment_rule_menu(){
  	$items['appointment_rule'] = array(
		'title' => '教室預約系統使用說明',
		'page callback' => 'appointment_rule_page',
		'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM
	);

	$items['appointment_rule/edit'] = array(
		'title' => '教室預約系統規則',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('appointment_rule_form'),
		'callback arguments' => array($form,&$form_state),
		'access callback' => 'user_access',
		'access arguments' => array('edit rule'),
		'type' => MENU_CALLBACK
	);
	return $items;
}

function appointment_rule_page(){
  	$sql = 'SELECT * FROM `as_rule`';
	$result = db_query($sql)->fetchObject();
  	//show annouce by javascirpt
	if(strlen($result->announce)>0){
		if(date('Y-m-d') <= $result->expiry_date){ //check if over expiry date
        		$announce = "alert('".$result->announce."');";
                	drupal_add_js($announce,'inline');
		}
	}


	//show rules and contact information
  	$output = '';
	$output .= $result->rule; 
	$output .= "\n<hr>\n";
	$output .= $result->contact;
	return $output;
}

function appointment_rule_permission(){
	return array(
		'edit rule' => array(
			'title' => t('Edit Appointment Rule'),
			'description' => 'Allow users edit the rule of appointment system.'
		),
	);
}

function appointment_rule_form($form, &$form_state){
	$sql = 'SELECT * FROM `as_rule`';
	$result = db_query($sql)->fetchObject();
	$form = array();
	$form['announce_set'] =array(
		'#type' => 'fieldset',
		'#title' => t('系辦公告'),
	);
	$form['announce_set']['announce'] = array(
		'#type' =>'textfield',
		'#default_value' => $result->announce,
		'#title' =>t('公告內容'),
	);
	if($result->expiry_date != null)
        	$tmp = explode('-',$result->expiry_date);
	else
		$tmp = explode('-',date('Y-m-d'));
        $date = array('year'=>$tmp[0],'month'=>intval($tmp[1]),'day'=>intval($tmp[2]));
	$form['announce_set']['expiry_date'] = array(
		'#type' =>'date',
		'#title' =>t('有效日期'),
		'#default_value' => $date
	);
	$form['rule'] = array(
		'#type' =>'textarea',
		'#title' =>t('預約規則'),
		'#default_value' => $result->rule
	);
	$form['contact'] = array(
		'#type' =>'textfield',
		'#default_value' => $result->contact,
		'#size' => 150,
		'#title' =>t('聯絡資訊'),
	);
	$form['submit'] = array(
		'#type'=>'submit',
		'#value'=>'確定',
		'#submit'=>array('appointment_rule_form_submit'),
	);
	return $form;
}

function appointment_rule_form_submit($form_id, &$form_state){
	$announce = $form_state['values']['announce'];
	$rule = $form_state['values']['rule'];
	$expiry_date =
                $form_state['values']['expiry_date']['year'].'-'.
                $form_state['values']['expiry_date']['month'].'-'.
                $form_state['values']['expiry_date']['day'];
	$contact = $form_state['values']['contact'];

	$sql = 'UPDATE `as_rule` SET `announce` = \''.$announce.'\', `expiry_date` = \''.$expiry_date.'\', `rule` = \''.$rule.'\', `contact`=\''.$contact.'\'';
	mysql_real_escape_string($sql);
	db_query($sql);
	drupal_goto('appointment_rule');
}

