<?php
require_once(DRUPAL_ROOT.'/sites/all/modules/appointment/config.inc');

function appointment_restrict_block_info(){
	$blocks['add_restriction'] = array(
		'info' => t('Add Restriction'),
    'status' => TRUE,
    'region' => 'sidebar_second',
    'weight' => 0,
    'visibility' => 0,
  );
  return $blocks;
}

function appointment_restrict_block_view($delta){
	switch($delta){
		case 'add_restriction':
  		$block['subject'] = t('Add Restriction');
  		$block['content'] = appointment_restrict_block_contents($delta);
			break;
  }
	return $block;
}

function appointment_restrict_block_contents($delta){
	switch($delta){
		case 'add_restriction':
			$output = drupal_render(drupal_get_form('add_restriction_form'));
			break;
	}
	return $output;
}


function appointment_restrict_menu(){
	$items['appointment_restrict']=array(
			'title' => 'Restriction List',
			'page callback' => 'appointment_restrict_page',
			'access callback' => 'user_access',
			'access arguments' => array('manage restriction'),	
			'type' => MENU_NORMAL_ITEM,
	);
	$items['appointment_restrict/delete']=array(
			'title' => 'Delete Restirction',
			'page callback' => 'delete_restriction',
			'access callback' => 'user_access',
			'access arguments' => array('manage restriction'),	
			'type' => MENU_CALLBACK,
	);
	return $items;
}

function appointment_restrict_permission(){
	return array(
		'manage restriction' => array(
			'title' => t('Manager restriction'),
			'description' => t('Allow users manager the list of restriction.'),
		),
	);
}

function delete_restriction($rid){
	$success = db_delete('restriction')
		->condition('rid',$rid)
		->execute();
	if($success!=null)
		drupal_set_message('Delete Restriction '.$rid.' Success');
	else
		drupal_set_message('Delete Restriction '.$rid.' Failed','error');	
	
	drupal_goto('appointment_restrict');
	return;
}

function appointment_restrict_page(){
	$result = db_query('SELECT * FROM restriction ORDER BY start_date');
	$period = get_period();
	$rows = array();
	foreach($result as $row){
		$delete = 
			'<a href="appointment_restrict/delete/'.$row->rid.'"><img src="sites/all/modules/appointment/images/b_drop.png" /></a>';
		$rows[] = array($row->name, $row->start_date,$row->end_date,$period[$row->start_period],$period[$row->end_period],$delete);
	}
	$headers = array('Name','Start Date','End Date','Start Period','End Period','Delete');
	
	$output = theme(
		'table',
		array(
			'header' => $headers,
			'rows' => $rows
		)
	);
	return $output;
}

function add_restriction_form($form, &$form_state){
	$form['rid'] = array(
		'#type'=>'hidden',
		'#value'=>$rid,
	);
 	$form['name'] = array(
     	'#type'=>'textfield',
     	'#title'=>t('Restriction'),
			'#size'=>15
  );
  $form['start_date'] = array(
    '#type'=>'date',
  	'#title'=>t('Start Date'),
  );
  $form['end_date'] = array(
    '#type'=>'date',
  	'#title'=>t('Start Date'),
  );
	$form['start_period'] = array(
		'#type'=>'select',
		'#title'=>t('Start Period'),
		'#options'=>get_period(),
		'#default_value' => 0
	);
	$form['end_period'] = array(
		'#type'=>'select',
		'#title'=>t('End Period'),
		'#options'=>get_period(),
		'#default_value' => 13 
	);
  $form['submit'] = array('#type'=>'submit', '#value'=>'Add');
	return $form;
}

function add_restriction_form_submit($form, &$form_state){
	$start_date = date('Y-m-d',mktime(0,0,0,
		$form_state['values']['start_date']['month'],
		$form_state['values']['start_date']['day'],
		$form_state['values']['start_date']['year']));

	$end_date = date('Y-m-d',mktime(0,0,0,
		$form_state['values']['end_date']['month'],
		$form_state['values']['end_date']['day'],
		$form_state['values']['end_date']['year']));

	$start_period = $form_state['values']['start_period'];
	$end_period = $form_state['values']['end_period'];

	if($start_date > $end_date){
		form_set_error('start_date','restrict date error');
		return;
	}
	else if($start_period > $end_period){
		form_set_error('start_period','restrict period error');
		return;
	}

	$holiday = array(
			'type' => 'holiday',
			'name' => $form_state['values']['name'],
			'start_date' => $start_date,
			'end_date' => $end_date,
			'start_period' => $form_state['values']['start_period'],
			'end_period' => $form_state['values']['end_period']);

	$special = array(
			'type' => 'special',
			'name' => $form_state['values']['name'],
			'start_date' => $start_date,
			'end_date' => $end_date,
			'start_period' => $form_state['values']['start_period'],
			'end_period' => $form_state['values']['end_period']);

	if(($start_date == $end_date)
		 && ($form_state['values']['start_period']==0 && $form_state['values']['end_period']==13))
		db_insert('restriction')
			->fields($holiday)
			->execute();
	else
		db_insert('restriction')
			->fields($special)
			->execute();
		
}
