<?php
require_once(DRUPAL_ROOT.'/sites/all/modules/appointment/config.inc');

function appointment_course_block_info(){
  $blocks['add_schedule'] = array(
    'info' => t('新增課表'),
    'status' => TRUE,
    'region' => 'sidebar_second',
    'weight' => 0,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'timetable/*'
  );
  $blocks['delete_schedule'] = array(
    'info' => t('刪除課表'),
    'status' => TRUE,
    'region' => 'sidebar_second',
    'weight' => 0,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'timetable/*'
  );
  $blocks['add_course'] = array(
    'info' => t('新增課程'),
    'status' => TRUE,
    'region' => 'sidebar_second',
    'weight' => 0,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'appointment_course'
  );
  return $blocks;
}

function appointment_course_block_view($delta){
  switch($delta){
    case 'add_schedule':
      $block['subject'] = t('新增課表');
      $block['content'] = appointment_course_block_contents($delta);
      break;
    case 'delete_schedule':
      $block['subject'] = t('刪除課表');
      $block['content'] = appointment_course_block_contents($delta);
      break;
    case 'add_course':
      $block['subject'] = t('新增課程');
      $block['content'] = appointment_course_block_contents($delta);
      break;
  }
  return $block;
}

function appointment_course_block_contents($delta){
  switch($delta){
    case 'add_schedule':
      $form = drupal_get_form('add_schedule_form');
      $output = drupal_render($form);
      break;
    case 'delete_schedule':
      $form = drupal_get_form('delete_schedule_form');
      $output = drupal_render($form);
      break;
    case 'add_course':
      $form = drupal_get_form('add_course_form');
      $output = drupal_render($form);
      break;
  }
  return $output;
}


function appointment_course_menu(){
	$items['appointment_course']=array(
			'title' => '課程列表',
			'page callback' => 'appointment_course_page',
			'access callback' => 'user_access',
			'access arguments' => array('manage course'),	
			'type' => MENU_NORMAL_ITEM,
	);
	$items['appointment_course/delete']=array(
			'title' => 'Appointment Course',
			'page callback' => 'delete_course',
			'access callback' => 'user_access',
			'access arguments' => array('manage course'),	
			'type' => MENU_CALLBACK,
	);
	$items['appointment_course/edit']=array(
			'title' => 'Appointment Course',
			'page callback' => 'edit_course',
			'access callback' => 'user_access',
			'access arguments' => array('manage course'),	
			'type' => MENU_CALLBACK,
	);
	$items['timetable']=array(
			'title' => '學期課表',
			'page callback' => 'list_classroom',
			'access callback' => 'user_access',
			'access arguments' => array('manage course'),	
			'type' => MENU_NORMAL_ITEM,
	);
	$sql = 'SELECT * FROM as_classroom';
	$result = db_query($sql);
	foreach($result as $row){
	  $items['timetable/'.$row->serial]=array(
	      'title' => $row->serial,
	      'page callback' => 'timetable',
	      'page arguments' => array($row->cid),
	      'access callback' => 'user_access',
	      'access arguments' => array('manage course'),	
	      'type' => MENU_NORMAL_ITEM,
	  );
	}
	return $items;
}

function appointment_course_permission(){
	return array(
		'manage course' => array(
			'title' => t('Manager course'),
			'description' => t('Allow users manager the list of course.'),
		),
	);
}

function delete_course($crid){
	$success = db_delete('as_course')
		->condition('crid',$crid)
		->execute();
	if($success!=null)
		drupal_set_message('刪除課程成功!');
	else
		drupal_set_message('刪除課程失敗!','error');	
	
	drupal_goto('appointment_course');
	return;
}

function edit_course($arg){
	switch($arg){
		case 'teacher':
			$success = db_update('as_course')
				->fields(array(
					'teacher' => $_POST['new_teacher']
			))
			->condition('crid',$_POST['crid'],'=')
			->execute();
			if($success != null)
				drupal_set_message('更新授課老師成功!');
			else
				drupal_set_message('更新授課老師失敗','error');
			drupal_goto('appointment_course');
			break;
		case 'name':
			$success = db_update('as_course')
				->fields(array(
					'name' => $_POST['new_name']
			))
			->condition('crid',$_POST['crid'],'=')
			->execute();
			if($success != null)
				drupal_set_message('更新課程名稱成功!');
			else
				drupal_set_message('更新課程名稱失敗!','error');
			drupal_goto('appointment_course');
			break;

	return;
	}
	
}

function appointment_course_page(){
  $result = db_query('SELECT * FROM `as_course` ORDER BY `name`');
  $rows = array();
  foreach($result as $row){
    $rename = '
      <center>
      <form name="edit_name" action="appointment_course/edit/name" method="post">
      更改課程名稱為:
      <input name="new_name" type="text" />
      <input name="crid" type="hidden" value="'.$row->crid.'" />
      <input type="submit" value="更改" />
      </form>
      <form name="edit_teacher" action="appointment_course/edit/teacher" method="post">
      更改授課老師為:
      <input name="new_teacher" type="text" />
      <input name="crid" type="hidden" value="'.$row->crid.'" />
      <input type="submit" value="更改" />
      </form>
      </center>';
    $delete = 
      '<a href="appointment_course/delete/'.$row->crid.'"><img src="sites/all/modules/appointment/images/b_drop.png" /></a>';
    $rows[] = array($row->name, $row->teacher,$rename,$delete);
  }
  $headers = array('課程名稱', '授課老師','','刪除');

  $output = theme(
    'table',
    array(
      'header' => $headers,
      'rows' => $rows
    )
  );
  return $output;
}

function list_classroom(){
  $sql = 'SELECT * FROM as_classroom';
  $result = db_query($sql);
  $rows = array();
  global $base_path;
  foreach($result as $row){
    $rows[] = '<a href="'.$base_path.'timetable/'.$row->serial.'">'.$row->serial.'</a>';
  }
	
  return theme('item_list',array('items'=>$rows));
}

function timetable($cid){
	$weekdays = get_weekday();
	$header = array(
		'',
		$weekdays[0],
		$weekdays[1],
		$weekdays[2],
		$weekdays[3],
		$weekdays[4],
		$weekdays[5],
		$weekdays[6],
	);
	$rows = array();	
	$period_joint = get_period_joint();
	$period_time = get_period_time();
	for($i=0;$i<14;$i++){
		$rows[$i]=array(8);
		for($j=1;$j<8;$j++)
			$rows[$i][$j]=array('width'=>'12%');
		$rows[$i][0]	= $period_joint[$i].' '.$period_time[$i];
		$cid_condition = 'cid='.$cid;
		$sql = 'SELECT * FROM as_timetable WHERE '.$cid_condition;
		$result = db_query($sql);
		foreach($result as $row){
			$sql = 'SELECT * FROM as_course WHERE crid='.$row->crid;
			$course = db_query($sql)->fetchObject();
			$coursename = $course->name.'<br />'.$course->teacher;
			if($i>=$row->start_period && $i<=$row->end_period){
				$rows[$i][$row->weekday+1]=array('data'=>$coursename,'width'=>'12%','style'=>'color:purple');
			}
		}		
	}
	$output = theme('table',array(
		'header'=>$header,
		'rows'=>$rows
		)
	);
	return $output;
}

function add_course_form($form, &$form_state){
  $form = array();
  $form['name'] = array(
    '#type'=>'textfield',
    '#title'=>t('課程名稱'),
    '#size'=>20,
  );
  $form['teacher'] = array(
    '#type'=>'textfield',
    '#title'=>t('授課老師'),
    '#size'=>20,
  );
  $form['submit'] = array('#type'=>'submit', '#value'=>'新增');
  return $form;
}

function add_course_form_submit($form, &$form_state) {
  db_insert('as_course')
    ->fields(array(
      'crid' => NULL,
      'name' => $form_state['values']['name'],
      'teacher' => $form_state['values']['teacher']
    ))
    ->execute();
}

function add_schedule_form($form, &$form_state){
	$serial = substr($_SERVER['QUERY_STRING'],12,4);
	$cid = get_classroom_info($serial)->cid;
	$form = array();
	$sql = 'SELECT * FROM as_course ORDER BY name';
	$result = db_query($sql);
	$courselist = array();
	foreach($result as $row)
		$courselist[$row->crid] = $row->name.' '.$row->teacher;
 	$form['name'] = array(
     	'#type'=>'select',
     	'#title'=>t('課程名稱'),
			'#options'=>$courselist
  );
	$form['cid'] = array(
		'#type'=>'hidden',
		'#value'=>$cid,
	);
  $form['weekday'] = array(
    '#type'=>'select',
  	'#title'=>t('星期'),
		'#options'=>get_weekday(),
		'#default_value' => 1 
  );
	$form['start_period'] = array(
		'#type'=>'select',
		'#title'=>t('從'),
		'#options'=>get_period(),
		'#default_value' => 0
	);
	$form['end_period'] = array(
		'#type'=>'select',
		'#title'=>t('到'),
		'#options'=>get_period(),
		'#default_value' => 0
	);
  $form['submit'] = array('#type'=>'submit', '#value'=>'新增');
	return $form;
}

function add_schedule_form_submit($form, &$form_state){
	db_insert('as_timetable')
		->fields(array(
			'cid' => $form_state['values']['cid'],
			'crid' => $form_state['values']['name'],
			'weekday' => $form_state['values']['weekday'],
			'start_period' => $form_state['values']['start_period'],
			'end_period' => $form_state['values']['end_period'],
		))
		->execute();
}

function delete_schedule_form($form, &$form_state){
  $weekdays = get_weekday();
	$period_joint = get_period_joint();
	$period_time = get_period_time();
	$serial = substr($_SERVER['QUERY_STRING'],12,4);
	$cid = get_classroom_info($serial)->cid;
	$sql = 'SELECT * FROM as_timetable WHERE cid='.$cid.' ORDER BY weekday';	
	$result = db_query($sql);
	$courselist = array();
	foreach($result as $row){
		$sql = 'SELECT name,teacher FROM as_course WHERE crid='.$row->crid;
		$course = db_query($sql)->fetchObject();
		$courselist[$row->id] = 
			$course->name.' '.$course->teacher.' '.
			$weekdays[$row->weekday].' '.
			$period_joint[$row->start_period].'~'.$period_joint[$row->end_period];
	}
	$form = array();
	$form['timetable'] = array(
     	'#type'=>'select',
     	'#title'=>t('課程名稱'),
			'#options'=>$courselist
	);
  $form['submit'] = array('#type'=>'submit', '#value'=>'刪除');
	return $form;
}

function delete_schedule_form_submit($form, &$form_state){
	db_delete('as_timetable')
		->condition('id',$form_state['values']['timetable'])
		->execute();
}
